name: CI / Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install Backend
      - name: Install Backend dependencies
        working-directory: ./Backend
        run: npm install

      # Install Frontend
      - name: Install Frontend dependencies
        working-directory: ./Frontend
        run: npm install

      # Build Frontend
      - name: Build Frontend for production
        working-directory: ./Frontend
        run: npm run build

  deploy:
    needs: build # The deploy step will only run if the build step passes
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #  your build commands
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v28 # deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          vercel-args: --prod # Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} # Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} # Required
          working-directory: Frontend
